[project]
authors = ["Olivier Grisel <olivier.grisel@ensta.org>"]
channels = ["conda-forge"]
description = "Experimental case study for ML-based battery operations"
name = "batteryops"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11.0,<4"
scipy = ">=1.14.1,<2"


[pypi-dependencies]
numpy = ">=2.1.0,<3"
pandas = ">=2.2.2,<3"
requests-cache = ">=1.2.1,<2"
requests = ">=2.32.3,<3"
openmeteo-requests = ">=1.3.0, <2"
retry-requests = ">=2.0.0, <3"
certifi = "*"
ipykernel = ">=6.29.5, <7"
matplotlib = ">=3.9.2, <4"

# Extra dev dependencies
